# For more information about the configurations used
# in this file, please see the Travis CI documentation.
#
# https://docs.travis-ci.com

install:
  - npx yarn install && npx yarn build

language: generic

matrix:
  include:
    - os: linux
      dist: trusty

notifications:
  email:
    on_failure: always
    on_success: never

sudo: required
